services:
  steamsalty:
    image: watn3y/steamsalty:master
    container_name: steamsalty
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TELEGRAMAPITOKEN=
      - STEAMAPIKEY=
      - DebugMode=false
      - CHATID=123
      - WATCHERS=123,456,789
      - SLEEPINTERVAL=60