name: Build and Push to Docker Hub on push to any branch

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:commit-${{ github.sha }}